openapi: 3.0.0
info:
  description: ワイン情報サーバの API仕様
  version: 0.0.6
  title: VWC Server API
  contact: {}
tags:
  - name: wine-api-controller
    description: Wine API Controller
paths:
  /api/v1/wine/colors:
    get:
      tags:
        - wine-api-controller
      summary: showColors
      operationId: showColorsUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/countries:
    get:
      tags:
        - wine-api-controller
      summary: showCountries
      operationId: showCountriesUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/makers:
    get:
      tags:
        - wine-api-controller
      summary: showMakers
      operationId: showMakersUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/ratings:
    get:
      tags:
        - wine-api-controller
      summary: showRatings
      operationId: showRatingsUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/regions:
    get:
      tags:
        - wine-api-controller
      summary: showRegions
      operationId: showRegionsUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/tastes:
    get:
      tags:
        - wine-api-controller
      summary: showTastes
      operationId: showTastesUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/varieties:
    get:
      tags:
        - wine-api-controller
      summary: showVarieties
      operationId: showVarietiesUsingGET
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  /api/v1/wine/wines:
    get:
      tags:
        - wine-api-controller
      summary: showWines
      operationId: showWinesUsingGET
      parameters:
        - name: countryCode
          in: query
          description: countryCode
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
  "/api/v1/wine/wines/{wineId}":
    get:
      tags:
        - wine-api-controller
      summary: showWineByWineId
      operationId: showWineByWineIdUsingGET
      parameters:
        - name: wineId
          in: path
          description: wineId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
            text/xml:
              schema:
                $ref: "#/components/schemas/WineAPIResponse"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      deprecated: false
servers:
  - url: //172.16.131.11:8080/
components:
  schemas:
    WineAPIResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
        statusCode:
          type: integer
          format: int32
      title: WineAPIResponse

