apiVersion: apps/v1
kind: Deployment
metadata:
  name: vwc-server-db-mysql
  annotations:
    app: vwc-server-db-mysql
    backstage.io/kubernetes-id: vwc-server-db-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vwc-server-db-mysql
  template:
    metadata:
      labels:
        app: vwc-server-db-mysql
        backstage.io/kubernetes-id: vwc-server-db-mysql
    spec:
      containers:
        - name: vwc-server-db-mysql
#          image: mysql/mysql-server:5.7.23
          image: mysql/mysql-server
          args:
#            - "--ignore-db-dir=lost+found"
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
#          envFrom:
#            - secretRef:
#                name: mysql-server-credentials
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: vwcpassword
            - name: MYSQL_DATABASE
              value: vwcserverdb
            - name: MYSQL_USER
              value: vwcuser
            - name: MYSQL_PASSWORD
              value: vwcpassword
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pvc
