---
apiVersion: v1
kind: Service
metadata:
  name: vwc-server-db-mysql
  annotations:
    app: vwc-server-db-mysql
    backstage.io/kubernetes-id: vwc-server-db-mysql
spec:
  type: LoadBalancer
  selector:
    app: vwc-server-db-mysql
  ports:
    - port: 3306
      targetPort: 3306

